import React from 'react';

export default [
  {
    w: 100,
    h: 50,
    x: 0,
    y: 0,
    id: '-1',
    children:<>1</>
    // isResizable: false,
    // isDraggable: false,
  },
  // undefined,
  {
    w: 50,
    h: 50,
    x: 40,
    y: 10,
    id: '0',
    children:<>2</>
    // isResizable: false,
    // isDraggable: false,
  },
  // {
  //   w: 1619,
  //   h: 930,
  //   x: 462,
  //   y: 110,
  //   id: '1',
  //   isResizable: false,
  //   isDraggable: false,
  // },
  // {
  //   w: 398,
  //   h: 930,
  //   x: 2106,
  //   y: 110,
  //   id: '2',
  //   isResizable: false,
  //   isDraggable: false,
  // },
  // {
  //   w: 1048,
  //   h: 121,
  //   x: 2528,
  //   y: 110,
  //   id: '3',
  //   isResizable: false,
  //   isDraggable: false,
  // },
  // {
  //   w: 1048,
  //   h: 121,
  //   x: 4493,
  //   y: 110,
  //   id: '4',
  //   isResizable: false,
  //   isDraggable: false,
  // },
  // {
  //   w: 398,
  //   h: 930,
  //   x: 5565,
  //   y: 110,
  //   id: '5',
  //   isResizable: false,
  //   isDraggable: false,
  // },
  // {
  //   w: 2042,
  //   h: 930,
  //   x: 5987,
  //   y: 110,
  //   id: '6',
  //   isResizable: false,
  //   isDraggable: false,
  // },
]
